### ISSUE TITLE
[napari 0.6.0] Render plane manipulator widget cannot be opened

### ISSUE THREAD

**Issue by psobolewskiPhD** [napari-threedee/napari-threedee#262]
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
File ~/micromamba/envs/napari-060/lib/python3.12/site-packages/app_model/backends/qt/_qaction.py:59, in QCommandAction._on_triggered(self=QMenuItemAction(MenuItem(when=None, group='3_plu...r (napari-threedee)'))), alt=None), app='napari'), checked=True)
     55 def _on_triggered(self, checked: bool) -> None:
     56     # execute_command returns a Future, for the sake of eventually being
     57     # asynchronous without breaking the API.  For now, we call result()
     58     # to raise any exceptions.
---> 59     self._app.commands.execute_command(self._command_id).result()
        self._command_id = 'napari-threedee:render plane manipulator'
        self = QMenuItemAction(MenuItem(when=None, group='3_plugin_contributions', order=None, command=CommandRule(id='napari-threedee:render plane manipulator', title='render plane manipulator', category=None, tooltip=None, status_tip=None, icon=None, icon_visible_in_menu=True, enablement=None, short_title=None, toggled=ToggleRule(condition=None, get_current=functools.partial(<function _get_current_dock_status at 0x11e0b5c60>, full_name='render plane manipulator (napari-threedee)'))), alt=None), app='napari')
        self._app = Application('napari')
File ~/micromamba/envs/napari-060/lib/python3.12/site-packages/app_model/registries/_commands_reg.py:247, in CommandsRegistry.execute_command(self=<CommandsRegistry at 0x11e0cf4a0 (171 commands)>, id='napari-threedee:render plane manipulator', execute_asynchronously=False, *args=(), **kwargs={})
    243 except Exception as e:
    244     if self._raise_synchronous_exceptions:
    245         # note, the caller of this function can also achieve this by
    246         # calling `future.result()` on the returned future object.
--> 247         raise e
    248     future.set_exception(e)
    250 return future

File ~/micromamba/envs/napari-060/lib/python3.12/site-packages/app_model/registries/_commands_reg.py:242, in CommandsRegistry.execute_command(self=<CommandsRegistry at 0x11e0cf4a0 (171 commands)>, id='napari-threedee:render plane manipulator', execute_asynchronously=False, *args=(), **kwargs={})
    240 future: Future = Future()
    241 try:
--> 242     future.set_result(cmd(*args, **kwargs))
        future = <Future at 0x15fc94140 state=pending>
        cmd = <function Store.inject.<locals>._inner.<locals>._exec at 0x15fb20860>
        args = ()
        kwargs = {}    243 except Exception as e:
    244     if self._raise_synchronous_exceptions:
    245         # note, the caller of this function can also achieve this by
    246         # calling `future.result()` on the returned future object.

File ~/micromamba/envs/napari-060/lib/python3.12/site-packages/in_n_out/_store.py:934, in Store.inject_processors.<locals>._deco.<locals>._exec(*args=(), **kwargs={})
    932 @wraps(func)
    933 def _exec(*args: P.args, **kwargs: P.kwargs) -> R:
--> 934     result = func(*args, **kwargs)
        func = <function Store.inject.<locals>._inner.<locals>._exec at 0x15fb209a0>
        args = ()
        kwargs = {}    935     if result is not None:
    936         self.process(
    937             result,
    938             type_hint=type_hint,
   (...)    941             _funcname=getattr(func, "__qualname__", str(func)),
    942         )

File ~/micromamba/envs/napari-060/lib/python3.12/site-packages/in_n_out/_store.py:804, in Store.inject.<locals>._inner.<locals>._exec(*args=(), **kwargs={})
    797 logger.debug(
    798     "  Calling %s with %r (injected %r)",
    799     _fname,
    800     bound.arguments,
    801     _injected_names,
    802 )
    803 try:
--> 804     result = func(**bound.arguments)
        bound = <BoundArguments (plugin='napari-threedee', widget_name='render plane manipulator', full_name='render plane manipulator (napari-threedee)')>
        func = functools.partial(<function _toggle_or_get_widget at 0x11e0b5bc0>, plugin='napari-threedee', widget_name='render plane manipulator', full_name='render plane manipulator (napari-threedee)')
        bound.arguments = {'plugin': 'napari-threedee', 'widget_name': 'render plane manipulator', 'full_name': 'render plane manipulator (napari-threedee)'}    805 except TypeError as e:
    806     if "missing" not in e.args[0]:

File ~/micromamba/envs/napari-060/lib/python3.12/site-packages/napari/_qt/_qplugins/_qnpe2.py:348, in _toggle_or_get_widget(plugin='napari-threedee', widget_name='render plane manipulator', full_name='render plane manipulator (napari-threedee)')
    346 if widget_param:
    347     kwargs[widget_param] = viewer
--> 348 return widget_callable(**kwargs), full_name
        kwargs = {'viewer': Viewer(camera=Camera(center=(50.422412021924714, 104.71186581432744, 154.95954661773365), zoom=np.float64(2.6347377441773085), angles=(np.float64(-167.57937756731596), np.float64(-1.5555263957361127), np.float64(64.01508051488003)), perspective=0.0, mouse_pan=True, mouse_zoom=True, orientation=(<DepthAxisOrientation.TOWARDS: 'towards'>, <VerticalAxisOrientation.DOWN: 'down'>, <HorizontalAxisOrientation.RIGHT: 'right'>)), cursor=Cursor(position=(np.float64(-33.46207218691836), np.float64(-58.0426929370446), np.float64(4.120170028831609)), scaled=True, style=<CursorStyle.STANDARD: 'standard'>, size=1.0), dims=Dims(ndim=3, ndisplay=3, order=(0, 1, 2), axis_labels=('0', '1', '2'), rollable=(True, True, True), range=(RangeTuple(start=np.float64(0.0), stop=np.float64(59.0), step=np.float64(1.0)), RangeTuple(start=np.float64(0.0), stop=np.float64(255.0), step=np.float64(1.0)), RangeTuple(start=np.float64(0.0), stop=np.float64(255.0), step=np.float64(1.0))), margin_left=(0.0, 0.0, 0.0), margin_right=(0.0, 0.0, 0.0), point=(np.float64(29.0), np.float64(127.0), np.float64(127.0)), last_used=0), grid=GridCanvas(stride=1, shape=(-1, -1), enabled=False, spacing=0.0), layers=[<Image layer 'membrane' at 0x12f373320>, <Image layer 'nuclei' at 0x13ca0f7d0>], help='use <2> for transform', status={'layer_name': 'nuclei', 'layer_base': 'nuclei', 'source_type': 'sample', 'plugin': 'napari builtins', 'coordinates': ' [-33 -58 4]: ', 'coords': ' [-33 -58 4]', 'value': ''}, tooltip=Tooltip(visible=False, text=''), theme='dark', title='napari', mouse_over_canvas=True, mouse_move_callbacks=[], mouse_drag_callbacks=[], mouse_double_click_callbacks=[<function double_click_to_zoom at 0x11cd5ade0>], mouse_wheel_callbacks=[<function dims_scroll at 0x11cd5ad40>], _persisted_mouse_event={}, _mouse_drag_gen={}, _mouse_wheel_gen={}, _keymap={})}
        widget_callable = <class 'napari_threedee.manipulators._qt.qt_render_plane_manipulator.QtRenderPlaneManipulatorWidget'>
        full_name = 'render plane manipulator (napari-threedee)'
File ~/micromamba/envs/napari-060/lib/python3.12/site-packages/napari_threedee/manipulators/_qt/qt_render_plane_manipulator.py:9, in QtRenderPlaneManipulatorWidget.__init__(self=<napari_threedee.manipulators._qt.qt_render_plane_manipulator.QtRenderPlaneManipulatorWidget object>, viewer=Viewer(camera=Camera(center=(50.422412021924714,...use_drag_gen={}, _mouse_wheel_gen={}, _keymap={}), *args=(), **kwargs={})
      8 def __init__(self, viewer: napari.Viewer, *args, **kwargs):
----> 9     super().__init__(model_class=RenderPlaneManipulator, viewer=viewer, *args, **kwargs)
        args = ()
        RenderPlaneManipulator = <class 'napari_threedee.manipulators.render_plane_manipulator.RenderPlaneManipulator'>
        viewer = Viewer(camera=Camera(center=(50.422412021924714, 104.71186581432744, 154.95954661773365), zoom=np.float64(2.6347377441773085), angles=(np.float64(-167.57937756731596), np.float64(-1.5555263957361127), np.float64(64.01508051488003)), perspective=0.0, mouse_pan=True, mouse_zoom=True, orientation=(<DepthAxisOrientation.TOWARDS: 'towards'>, <VerticalAxisOrientation.DOWN: 'down'>, <HorizontalAxisOrientation.RIGHT: 'right'>)), cursor=Cursor(position=(np.float64(-33.46207218691836), np.float64(-58.0426929370446), np.float64(4.120170028831609)), scaled=True, style=<CursorStyle.STANDARD: 'standard'>, size=1.0), dims=Dims(ndim=3, ndisplay=3, order=(0, 1, 2), axis_labels=('0', '1', '2'), rollable=(True, True, True), range=(RangeTuple(start=np.float64(0.0), stop=np.float64(59.0), step=np.float64(1.0)), RangeTuple(start=np.float64(0.0), stop=np.float64(255.0), step=np.float64(1.0)), RangeTuple(start=np.float64(0.0), stop=np.float64(255.0), step=np.float64(1.0))), margin_left=(0.0, 0.0, 0.0), margin_right=(0.0, 0.0, 0.0), point=(np.float64(29.0), np.float64(127.0), np.float64(127.0)), last_used=0), grid=GridCanvas(stride=1, shape=(-1, -1), enabled=False, spacing=0.0), layers=[<Image layer 'membrane' at 0x12f373320>, <Image layer 'nuclei' at 0x13ca0f7d0>], help='use <2> for transform', status={'layer_name': 'nuclei', 'layer_base': 'nuclei', 'source_type': 'sample', 'plugin': 'napari builtins', 'coordinates': ' [-33 -58 4]: ', 'coords': ' [-33 -58 4]', 'value': ''}, tooltip=Tooltip(visible=False, text=''), theme='dark', title='napari', mouse_over_canvas=True, mouse_move_callbacks=[], mouse_drag_callbacks=[], mouse_double_click_callbacks=[<function double_click_to_zoom at 0x11cd5ade0>], mouse_wheel_callbacks=[<function dims_scroll at 0x11cd5ad40>], _persisted_mouse_event={}, _mouse_drag_gen={}, _mouse_wheel_gen={}, _keymap={})
        kwargs = {}
File ~/micromamba/envs/napari-060/lib/python3.12/site-packages/napari_threedee/_backend/threedee_widget_base.py:25, in QtThreeDeeWidgetBase.__init__(self=<napari_threedee.manipulators._qt.qt_render_plane_manipulator.QtRenderPlaneManipulatorWidget object>, model_class=<class 'napari_threedee.manipulators.render_plane_manipulator.RenderPlaneManipulator'>, viewer=Viewer(camera=Camera(center=(50.422412021924714,...use_drag_gen={}, _mouse_wheel_gen={}, _keymap={}), flags=None, *args=(), **kwargs={})
     20 self.viewer = viewer
     22 self._layer_selection_widget = generate_populated_layer_selection_widget(
     23     func=self.model.set_layers, viewer=viewer
     24 )
---> 25 self._layer_selection_widget()
        self._layer_selection_widget = <FunctionGui set_layers(layers: napari.layers.image.image.Image = <Image layer 'membrane' at 0x12f373320>)>
        self = <napari_threedee.manipulators._qt.qt_render_plane_manipulator.QtRenderPlaneManipulatorWidget object at 0x1790d90a0>     27 # start in the disabled state
     28 self.activate_button = QPushButton('activate')

File ~/micromamba/envs/napari-060/lib/python3.12/site-packages/magicgui/widgets/_function_gui.py:351, in FunctionGui.__call__(self=<FunctionGui set_layers(layers: napari.layers.im...Image = <Image layer 'membrane' at 0x12f373320>)>, *args=(), **kwargs={})
    349 self._tqdm_depth = 0  # reset the tqdm stack count
    350 with _function_name_pointing_to_widget(self):
--> 351     value = self._function(*bound.args, **bound.kwargs)
        self = <FunctionGui set_layers(layers: napari.layers.image.image.Image = <Image layer 'membrane' at 0x12f373320>)>
        bound = <BoundArguments (layers=<Image layer 'membrane' at 0x12f373320>)>
        self._function = <bound method RenderPlaneManipulator.set_layers of <napari_threedee.manipulators.render_plane_manipulator.RenderPlaneManipulator object at 0x15fcd76e0>>    353 self._call_count += 1
    354 if self._result_widget is not None:

File ~/micromamba/envs/napari-060/lib/python3.12/site-packages/napari_threedee/manipulators/render_plane_manipulator.py:16, in RenderPlaneManipulator.set_layers(self=<napari_threedee.manipulators.render_plane_manipulator.RenderPlaneManipulator object>, layers=<Image layer 'membrane'>)
     15 def set_layers(self, layers: napari.layers.Image):
---> 16     super().set_layers(layers)
        layers = <Image layer 'membrane' at 0x12f373320>
File ~/micromamba/envs/napari-060/lib/python3.12/site-packages/napari_threedee/manipulators/base_manipulator.py:217, in BaseManipulator.set_layers(self=<napari_threedee.manipulators.render_plane_manipulator.RenderPlaneManipulator object>, layer=<Image layer 'membrane'>)
    211 def set_layers(self, layer: Type[napari.layers.Layer]):
    212     """Add the correct layer type for the manipulator in a subclass.
    213 
    214     Implementing this method with a correct type annotation will allow
    215     autogeneration of a Qt widget for a manipulator.
    216     """
--> 217     self.layer = layer
        layer = <Image layer 'membrane' at 0x12f373320>
        self = <napari_threedee.manipulators.render_plane_manipulator.RenderPlaneManipulator object at 0x15fcd76e0>
File ~/micromamba/envs/napari-060/lib/python3.12/site-packages/napari_threedee/manipulators/base_manipulator.py:243, in BaseManipulator.layer(self=<napari_threedee.manipulators.render_plane_manipulator.RenderPlaneManipulator object>, layer=<Image layer 'membrane'>)
    241 if self.layer is not None:
    242     self._disconnect_events()
--> 243 self._backend.layer = layer
        layer = <Image layer 'membrane' at 0x12f373320>
        self._backend = <napari_threedee._backend.manipulator.napari_manipulator_backend.NapariManipulatorBackend object at 0x13f284410>
        self = <napari_threedee.manipulators.render_plane_manipulator.RenderPlaneManipulator object at 0x15fcd76e0>    244 if self.enabled:
    245     self._on_enable()

File ~/micromamba/envs/napari-060/lib/python3.12/site-packages/napari_threedee/_backend/manipulator/napari_manipulator_backend.py:62, in NapariManipulatorBackend.layer(self=<napari_threedee._backend.manipulator.napari_manipulator_backend.NapariManipulatorBackend object>, layer=<Image layer 'membrane'>)
     60     self._disconnect_mouse_callback()
     61 self._layer = layer
---> 62 self._connect_vispy_visual()
        self = <napari_threedee._backend.manipulator.napari_manipulator_backend.NapariManipulatorBackend object at 0x13f284410>     63 self._connect_mouse_callback()

File ~/micromamba/envs/napari-060/lib/python3.12/site-packages/napari_threedee/_backend/manipulator/napari_manipulator_backend.py:74, in NapariManipulatorBackend._connect_vispy_visual(self=<napari_threedee._backend.manipulator.napari_manipulator_backend.NapariManipulatorBackend object>)
     73 def _connect_vispy_visual(self):
---> 74     parent = get_vispy_root_node(self._viewer, self.layer)
        self._viewer = Viewer(camera=Camera(center=(50.422412021924714, 104.71186581432744, 154.95954661773365), zoom=np.float64(2.6347377441773085), angles=(np.float64(-167.57937756731596), np.float64(-1.5555263957361127), np.float64(64.01508051488003)), perspective=0.0, mouse_pan=True, mouse_zoom=True, orientation=(<DepthAxisOrientation.TOWARDS: 'towards'>, <VerticalAxisOrientation.DOWN: 'down'>, <HorizontalAxisOrientation.RIGHT: 'right'>)), cursor=Cursor(position=(np.float64(-33.46207218691836), np.float64(-58.0426929370446), np.float64(4.120170028831609)), scaled=True, style=<CursorStyle.STANDARD: 'standard'>, size=1.0), dims=Dims(ndim=3, ndisplay=3, order=(0, 1, 2), axis_labels=('0', '1', '2'), rollable=(True, True, True), range=(RangeTuple(start=np.float64(0.0), stop=np.float64(59.0), step=np.float64(1.0)), RangeTuple(start=np.float64(0.0), stop=np.float64(255.0), step=np.float64(1.0)), RangeTuple(start=np.float64(0.0), stop=np.float64(255.0), step=np.float64(1.0))), margin_left=(0.0, 0.0, 0.0), margin_right=(0.0, 0.0, 0.0), point=(np.float64(29.0), np.float64(127.0), np.float64(127.0)), last_used=0), grid=GridCanvas(stride=1, shape=(-1, -1), enabled=False, spacing=0.0), layers=[<Image layer 'membrane' at 0x12f373320>, <Image layer 'nuclei' at 0x13ca0f7d0>], help='use <2> for transform', status={'layer_name': 'nuclei', 'layer_base': 'nuclei', 'source_type': 'sample', 'plugin': 'napari builtins', 'coordinates': ' [-33 -58 4]: ', 'coords': ' [-33 -58 4]', 'value': ''}, tooltip=Tooltip(visible=False, text=''), theme='dark', title='napari', mouse_over_canvas=True, mouse_move_callbacks=[], mouse_drag_callbacks=[], mouse_double_click_callbacks=[<function double_click_to_zoom at 0x11cd5ade0>], mouse_wheel_callbacks=[<function dims_scroll at 0x11cd5ad40>], _persisted_mouse_event={}, _mouse_drag_gen={}, _mouse_wheel_gen={}, _keymap={})
        self = <napari_threedee._backend.manipulator.napari_manipulator_backend.NapariManipulatorBackend object at 0x13f284410>     75     self.vispy_visual.parent = parent
     76     self.vispy_visual.transform = MatrixTransform()

File ~/micromamba/envs/napari-060/lib/python3.12/site-packages/napari_threedee/utils/napari_utils.py:65, in get_vispy_root_node(viewer=Viewer(camera=Camera(center=(50.422412021924714,...use_drag_gen={}, _mouse_wheel_gen={}, _keymap={}), layer=<Image layer 'membrane'>)
     62 # this will need to be updated in napari 0.5.0
     63 # viewer.window._qt_window._qt_viewer.canvas.view.scene
     64 qt_viewer = viewer.window._qt_window._qt_viewer
---> 65 return qt_viewer.view.scene
        qt_viewer = <napari._qt.qt_viewer.QtViewer object at 0x11e0adf40>
AttributeError: 'QtViewer' object has no attribute 'view'
```

**Comment by psobolewskiPhD** [comment]
In 0.5.6 there was a warning:
```
/Users/sobolp/micromamba/envs/napari-056/lib/python3.12/site-packages/napari_threedee/utils/napari_utils.py:65: FutureWarning: Access to QtViewer.view is deprecated since 0.5.0 and will be removed in the napari 0.6.0. Change to QtViewer.canvas.view instead.!
```


I think it's this part:
https://github.com/napari-threedee/napari-threedee/blob/f5abe53602f3a5cc861021781cb93c2d48fc0fb3/src/napari_threedee/utils/napari_utils.py#L57-L65

So can update this and then drop support for older napari?

**Comment by alisterburt** [comment]
thanks for spelunking! @aysecanuenal this will be necessary to get napari-tomoslice working on napari>=0.6.0 - if you're interested in working on this let me know otherwise I'll try to find time for it (no guarantees)

**Comment by psobolewskiPhD** [comment]
I can give it a whirl. I like to use napari-threedee in my workshops, even if just as a demo. and my workshop is Tuesday/Thrsuday 😬

**Comment by alisterburt** [comment]
works for me, good luck with the workshop and hope you're doing well! :)
